export const IMAGES = {
  chat: require('../assets/icons/speech-bubble.png'),
  status: require('../assets/icons/status.png'),
  call: require('../assets/icons/phone.png'),
  profile: require('../assets/icons/user.png'),
  camera: require('../assets/icons/camera.png'),
  choosegallery: require('../assets/icons/gallery.png'),
  gallery: require('../assets/icons/image.png'),
  search: require('../assets/icons/searchicon.png'),
  intro_1: require('../assets/images/intro_1.png'),
  intro_2: require('../assets/images/intro_2.png'),
  intro_3: require('../assets/images/intro_3.png'),
  logo: require('../assets/images/logo.png'),
  bg_image: require('../assets/images/Bg_image.png'), 
  videoCall: require('../assets/icons/video-camera.png'),
  more: require('../assets/icons/more.png'),
  back: require('../assets/icons/back.png'),
  phone: require('../assets/icons/phone-call.png'),
  send: require('../assets/icons/arrow-right.png'),
  emoji: require('../assets/icons/happiness.png'),
  attachment: require('../assets/icons/attach.png'),
  file: require('../assets/icons/file.png'),
  location: require('../assets/icons/location.png'),
  contact: require('../assets/icons/contact.png'),
  // Agar aur icons hain to yaha add karo
  userList: require('../assets/icons/userlist.png'),
};
